// <auto-generated />
using System;
using FicMart.PaymentGateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FicMart.PaymentGateway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentGatewayDbContext))]
    [Migration("20260819140941_CompletePaymentLifecycle")]
    partial class CompletePaymentLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("new_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_status");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId", "OccurredAt")
                        .HasDatabaseName("ix_audit_records_payment_occurred_at");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.AuthorizationAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankAuthorizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bank_authorization_id");

                    b.Property<Guid>("BankIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BankAuthorizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_authorization_attempts_bank_authorization_id");

                    b.HasIndex("BankIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_authorization_attempts_bank_idempotency_key");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_authorization_attempts_payment_id");

                    b.ToTable("authorization_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_authorization_attempts_bank_id", "(status = 'Succeeded' AND bank_authorization_id IS NOT NULL) OR (status <> 'Succeeded' AND bank_authorization_id IS NULL)");

                            t.HasCheckConstraint("ck_authorization_attempts_status", "status IN ('Pending', 'Succeeded', 'Rejected', 'Unknown')");

                            t.HasCheckConstraint("ck_authorization_attempts_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.CaptureAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankCaptureId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bank_capture_id");

                    b.Property<Guid>("BankIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BankCaptureId")
                        .IsUnique()
                        .HasDatabaseName("ux_capture_attempts_bank_capture_id");

                    b.HasIndex("BankIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_capture_attempts_bank_idempotency_key");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_capture_attempts_payment_id");

                    b.ToTable("capture_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_capture_attempts_bank_id", "(status = 'Succeeded' AND bank_capture_id IS NOT NULL) OR (status <> 'Succeeded' AND bank_capture_id IS NULL)");

                            t.HasCheckConstraint("ck_capture_attempts_status", "status IN ('Pending', 'Succeeded', 'Rejected', 'Unknown')");

                            t.HasCheckConstraint("ck_capture_attempts_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("Operation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Operation", "Key");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_idempotency_records_payment_id");

                    b.ToTable("idempotency_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_records_fingerprint", "char_length(request_fingerprint) = 64");

                            t.HasCheckConstraint("ck_idempotency_records_operation", "operation IN ('Authorize', 'Capture', 'Void', 'Refund')");

                            t.HasCheckConstraint("ck_idempotency_records_state", "state IN ('Processing', 'Retryable', 'Completed')");

                            t.HasCheckConstraint("ck_idempotency_records_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor_units");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("customer_id");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_order_id");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount_positive", "amount_minor_units > 0");

                            t.HasCheckConstraint("ck_payments_currency_usd", "currency = 'USD'");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('PendingAuthorization', 'Authorized', 'Declined', 'Captured', 'Voided', 'Refunded')");

                            t.HasCheckConstraint("ck_payments_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.ReconciliationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("detail_code");

                    b.Property<string>("Operation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId", "CreatedAt")
                        .HasDatabaseName("ix_reconciliation_records_payment_created_at");

                    b.ToTable("reconciliation_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_reconciliation_records_operation", "operation IS NULL OR operation IN ('Authorize', 'Capture', 'Void', 'Refund')");

                            t.HasCheckConstraint("ck_reconciliation_records_outcome", "outcome IN ('Recovered', 'NoActionRequired', 'OperatorReviewRequired', 'AlreadyProcessing', 'StillPending')");
                        });
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.RefundAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_idempotency_key");

                    b.Property<string>("BankRefundId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bank_refund_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BankIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_refund_attempts_bank_idempotency_key");

                    b.HasIndex("BankRefundId")
                        .IsUnique()
                        .HasDatabaseName("ux_refund_attempts_bank_refund_id");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_refund_attempts_payment_id");

                    b.ToTable("refund_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_refund_attempts_bank_id", "(status = 'Succeeded' AND bank_refund_id IS NOT NULL) OR (status <> 'Succeeded' AND bank_refund_id IS NULL)");

                            t.HasCheckConstraint("ck_refund_attempts_status", "status IN ('Pending', 'Succeeded', 'Rejected', 'Unknown')");
                        });
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.VoidAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_idempotency_key");

                    b.Property<string>("BankVoidId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bank_void_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BankIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_void_attempts_bank_idempotency_key");

                    b.HasIndex("BankVoidId")
                        .IsUnique()
                        .HasDatabaseName("ux_void_attempts_bank_void_id");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_void_attempts_payment_id");

                    b.ToTable("void_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_void_attempts_bank_id", "(status = 'Succeeded' AND bank_void_id IS NOT NULL) OR (status <> 'Succeeded' AND bank_void_id IS NULL)");

                            t.HasCheckConstraint("ck_void_attempts_status", "status IN ('Pending', 'Succeeded', 'Rejected', 'Unknown')");
                        });
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.AuditRecord", b =>
                {
                    b.HasOne("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.AuthorizationAttemptRecord", b =>
                {
                    b.HasOne("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.CaptureAttemptRecord", b =>
                {
                    b.HasOne("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.HasOne("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.ReconciliationRecord", b =>
                {
                    b.HasOne("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.RefundAttemptRecord", b =>
                {
                    b.HasOne("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.VoidAttemptRecord", b =>
                {
                    b.HasOne("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
