// <auto-generated />
using System;
using FicMart.PaymentGateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FicMart.PaymentGateway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentGatewayDbContext))]
    partial class PaymentGatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.AuthorizationAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankAuthorizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bank_authorization_id");

                    b.Property<Guid>("BankIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BankAuthorizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_authorization_attempts_bank_authorization_id");

                    b.HasIndex("BankIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_authorization_attempts_bank_idempotency_key");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_authorization_attempts_payment_id");

                    b.ToTable("authorization_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_authorization_attempts_bank_id", "(status = 'Succeeded' AND bank_authorization_id IS NOT NULL) OR (status <> 'Succeeded' AND bank_authorization_id IS NULL)");

                            t.HasCheckConstraint("ck_authorization_attempts_status", "status IN ('Pending', 'Succeeded', 'Rejected', 'Unknown')");

                            t.HasCheckConstraint("ck_authorization_attempts_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor_units");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("customer_id");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_order_id");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount_positive", "amount_minor_units > 0");

                            t.HasCheckConstraint("ck_payments_currency_usd", "currency = 'USD'");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('PendingAuthorization', 'Authorized', 'Declined', 'Captured', 'Voided', 'Refunded')");

                            t.HasCheckConstraint("ck_payments_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("FicMart.PaymentGateway.Infrastructure.Persistence.AuthorizationAttemptRecord", b =>
                {
                    b.HasOne("FicMart.PaymentGateway.Infrastructure.Persistence.PaymentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
